#!/usr/bin/env bash

set -euCo pipefail

function get_volume() {
  pamixer --get-volume
}

function get_muted() {
  pamixer --get-mute
}

function to_blocks() {
  seq -f '%02g' -s '' 1 5 $1 | sed 's/.\{2\}/■/g'
}

function to_spaces() {
  seq -s ' ' $1 5 100 | tr -d '[:digit:]'
}

function to_meters() {
  echo "[$(to_blocks $1)$(to_spaces $1)]"
}

function print_volume() {
  local -r volume=$(get_volume)
  [[ ${volume} -gt 100 ]] \
    && echo -e "${volume}\n" \
    || echo -e "$(to_meters ${volume})\n"
}

function main() {
  print_volume

  declare -Ar colors=( ['true']='#9790a4' ['false']='#e7e7eb' )
  echo "${colors[$(get_muted)]}"
}

main
